loading annotations into memory...
Done (t=9.58s)
creating index...
index created!
Traceback (most recent call last):
  File "./lib/train.py", line 199, in <module>
    train() #debug/train
  File "./lib/train.py", line 144, in train
    loss, net = mask_rcnn(X, True, gt_boxes=gt_boxes, gt_classes=gt_classes, gt_masks=gt_masks)
  File "/home/andy/original-mask-rcnn/lib/mask_rcnn.py", line 66, in mask_rcnn
    rpn_feats = tf.Print(feats, [tf.convert_to_tensor('fpn completed')])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/logging_ops.py", line 64, in Print
    return gen_logging_ops._print(input_, data, message, first_n, summarize, name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 363, in _print
    summarize=summarize, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'input' to a tensor and failed. Error: Dimension 1 in both shapes must be equal, but are 42 and 21. Shapes are [2,42,42,1024] and [2,21,21,2048].
	From merging shape 2 with other shapes. for 'Print_1/packed' (op: 'Pack') with input shapes: [2,168,168,256], [2,84,84,512], [2,42,42,1024], [2,21,21,2048].

real	0m16.196s
user	0m15.485s
sys	0m1.220s
